[package]
name = "client"
version.workspace = true
edition = "2021"

[dependencies]
backend-api.workspace = true

rpc = { workspace = true, features = ["client"] }

axum = { workspace = true, optional = true }
cfg-if.workspace = true
codee.workspace = true
garde.workspace = true
gloo-net.workspace = true
http.workspace = true
leptos.workspace = true
leptos_axum = { workspace = true, optional = true }
leptos_meta.workspace = true
leptos_reactive.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
serde.workspace = true
thiserror.workspace = true
tower-sessions = { workspace = true, optional = true }
tracing.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["v4", "fast-rng"] }

[features]
hydrate = [
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate",
]

ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "leptos-use/axum",
    "leptos-use/ssr",

    "dep:axum",
    "dep:leptos_axum",
    "dep:tower-sessions",
]
