services:
  server:
    build: . 
    restart: always
    secrets:
      - google_client_id
      - google_client_secret
      - postgres_password
      - redis_password
    env_file: ".env"
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    user: postgres
    secrets:
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ".env"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

