[package]
name = "service"
version.workspace = true
edition = "2021"

[dependencies]
entity = { path = "../entity" }
serde.workspace = true
strum.workspace = true
thiserror.workspace = true

[dependencies.sea-orm]
workspace = true
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-postgres",
]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
mock = ["sea-orm/mock"]

[[test]]
name = "mock"
required-features = ["mock"]